#!/bin/bash
#
#It's important to set the ANT_DOCBOOK_HOME environment variable to the location where you keep build-docbook.xml (without the trailing slash), since this script does not know where build-docbook.xml is or where itself is.
#
#export CLASSPATH="${CLASSPATH}:/etc/xml/:$(java-config --classpath saxon-bin,xml-commons,xml-commons-resolver,xml-commons-external-1.3)"
#
#some possible classpath packages under gentoo: xerces-2,xalan,saxon,saxon-bin,xml-commons,xml-commons-resolver,xml-commons-external-1.3
#
#echo ${CLASSPATH}
if [ -n "${ANT_DOCBOOK_HOME}" ]; then
    if [ -f "${ANT_DOCBOOK_HOME}/build-docbook.xml" ]; then
	ant -f ${ANT_DOCBOOK_HOME}/build-docbook.xml -Dbasedir="$(pwd)" "$@"
    else
	echo "build-docbook.xml was not found in ${ANT_DOCBOOK_HOME}. Please check that the ANT_DOCBOOK_HOME environment variable is set to the directory containing build-docbook.xml (without the trailing forward slash)."
    fi
else
    echo "Please set the ANT_DOCBOOK_HOME environment variable to the directory that contains build-docbook.xml (without the trailing forward slash)."
fi